services:
  budget-front:
    build:
      context: .
      dockerfile: Dockerfile
    image: budget-front
    environment:
      # Database and Port
      - API_URL=${API_URL}
      
    ports:
      - "${PORT}:3000"
