services:
  budget-front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${API_URL}
    image: budget-front
    environment:
      # Database and Port
      - NEXT_PUBLIC_API_URL=${API_URL}
      
    ports:
      - "${PORT}:3000"
